name = "remove-encoding-worker"
type = "javascript"

[env.production]
workers_dev = false
route = "https://sible.ai/*"
zone_id = "eeur"

[[bindings]]
type = "r2_bucket"
name = "MY_R2_BUCKET"
bucket_name = "sible-01"