name = "remove-encoding-worker"
main = "cloudflare-worker.js"
compatibility_date = "2025-03-14"
workers_dev = false

[env.production]
route = "https://sible.ai/*"
zone_id = "eeur"

[[env.production.bindings]]
type = "r2_bucket"
name = "MY_R2_BUCKET"
bucket_name = "sible-01"